---
  -  name: Setup playbook
     hosts: webservers
     become: true
     tasks:
       - name: Install python3-pip
         apt:
           name: python3-pip
           state: present
       - name: Install Docker
         apt:
           name: docker.io
           state: present
       - name: install docker pip
         pip:
           name: docker
           state: present
       - name: download and launch a docker web container
         docker_container:
           name: dvwa
           image: cyberxsecurity/dvwa
           state: started
           restart_policy: always
           ports:
             - "80:80"
       - name: Enable docker service
         systemd:
           name: docker
           enabled: yes